apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: camidzn/fastapi:initial
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_NAME
              value: "RealtorPriceModel"
            - name: MLFLOW_TRACKING_URI
              value: "http://10.43.101.196:30003"
            - name: DB_URL
              value: "postgresql://user:pass@db:5432/raw_data"
