apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: mlops
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          # Esta es la imagen que Kustomize reemplazará de "initial" a "20250531-18"
          image: camidzn/fastapi:initial
          ports:
            - containerPort: 8000
          env:
            # Nombre del modelo en MLflow Registry
            - name: MODEL_NAME
              value: "RealtorPriceModel"

            # URI del MLflow Tracking Server DENTRO del clúster
            #  - El service se llama 'mlflow-service' en namespace 'mlops'
            #  - Internamente, las aplicaciones lo resuelven como:
            #      http://mlflow-service.mlops.svc.cluster.local:5000
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-service.mlops.svc.cluster.local:5000"

            # Cadena de conexión PostgreSQL para raw_data
            #  - El service se llama 'postgres-service' en namespace 'mlops'
            #  - Credenciales según tu postgres-deployment.yaml: user=postgres, password=supersecret, db=mlflow
            - name: DB_URL
              value: "postgresql://postgres:supersecret@postgres-service.mlops.svc.cluster.local:5432/mlflow"

          # Probes para que Kubernetes verifique salud del contenedor
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
