apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - port: 8000        # Puerto interno del Service
      targetPort: 8000  # Puerto en que corre FastAPI dentro del contenedor
      nodePort: 30100   # Puerto expuesto en cada nodo (entre 30000–32767)
