apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: camidzn/fastapi:initial
          ports:
            - containerPort: 8000

          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://10.43.101.196:30003"
            - name: MLFLOW_MODEL_NAME
              value: "RealtorPriceModel"
            - name: RAW_DATA_DB_URI
              value: "mysql+pymysql://model_user:model_password@10.43.101.172:30306/RawData"
