apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini-overrides
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true
    org_role = Viewer

    [security]
    # (opcional) puedes definir usuario/password de admin si lo deseas, por ejemplo:
    # admin_user = admin
    # admin_password = admin
