apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
data:
  provisioning-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true

  provisioning-dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 600
        options:
          path: /var/lib/grafana/dashboards
