# CI trigger test 7
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana-configmap.yaml
- grafana-deployment.yaml
- grafana-service.yaml
- prometheus-configmap.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- streamlit-deployment.yaml
- streamlit-service.yaml
- api-deployment.yaml
- api-service.yaml

images:
- name: camidzn/fastapi
  newTag: 20250531-20
- name: camidzn/grafana
  newTag: 20250531-20
- name: camidzn/prometheus
  newTag: 20250531-20
- name: camidzn/streamlit-app
  newTag: 20250531-20
