# CI trigger test 7
resources:
- grafana-deployment.yaml
- grafana-service.yaml
- grafana-configmap.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- prometheus-configmap.yaml
- streamlit-deployment.yaml
- streamlit-service.yaml

images:
- name: camidzn/fastapi
  newTag: 20250527-5
- name: camidzn/grafana
  newTag: 20250527-5
- name: camidzn/prometheus
  newTag: 20250527-5
- name: camidzn/streamlit-app
  newTag: 20250527-5
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
