apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: mlops
spec:
  type: NodePort
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 31851
  selector:
    app: streamlit