apiVersion: batch/v1
kind: Job
metadata:
  name: create-minio-bucket
  namespace: mlops
spec:
  template:
    spec:
      containers:
        - name: create-bucket
          image: minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 10
              mc alias set local http://minio-service.mlops.svc.cluster.local:9000 admin supersecret
              mc mb local/mlflow
              mc policy set public local/mlflow
      restartPolicy: OnFailure
