apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - create-bucket-job.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - mlflow-deployment.yaml
  - mlflow-service.yaml
