apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: localhost:32000/custom-mlflow:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio-service:9000
        - name: AWS_ACCESS_KEY_ID
          value: admin
        - name: AWS_SECRET_ACCESS_KEY
          value: supersecret
        command:
        - mlflow
        - server
        - --backend-store-uri
        - postgresql+psycopg2://postgres:supersecret@postgres-service/mlflow
        - --default-artifact-root
        - s3://mlflows3/artifacts
        - --host
        - 0.0.0.0
        - --serve-artifacts
