apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proyecto-mlops-daniel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CamiDzN/Proyecto-MLOps
    targetRevision: main
    path: Servidor2/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
