name: CI/CD Servidor3

on:
  push:
    branches: [ main ]
    paths:
      - 'Servidor3/grafana/**'
      - 'Servidor3/prometheus/**'
      - 'Servidor3/streamlit/**'
      - 'Servidor3/fastapi/**'
      - 'Servidor3/k8s/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Definir IMAGE_TAG
        run: echo "IMAGE_TAG=$(date +'%Y%m%d')-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/grafana:${{ env.IMAGE_TAG }}    ./Servidor3/grafana
          docker build -t ${{ secrets.DOCKERHUB_USER }}/prometheus:${{ env.IMAGE_TAG }} ./Servidor3/prometheus
          docker build -t ${{ secrets.DOCKERHUB_USER }}/streamlit-app:${{ env.IMAGE_TAG }} ./Servidor3/streamlit
          docker build -t ${{ secrets.DOCKERHUB_USER }}/fastapi:${{ env.IMAGE_TAG }}           ./Servidor3/fastapi

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/grafana:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USER }}/prometheus:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USER }}/streamlit-app:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USER }}/fastapi:${{ env.IMAGE_TAG }}

      - name: Actualizar kustomization
        run: |
          cd Servidor3/k8s
          kustomize edit set image ${{ secrets.DOCKERHUB_USER }}/grafana:${{ env.IMAGE_TAG }}
          kustomize edit set image ${{ secrets.DOCKERHUB_USER }}/prometheus:${{ env.IMAGE_TAG }}
          kustomize edit set image ${{ secrets.DOCKERHUB_USER }}/streamlit-app:${{ env.IMAGE_TAG }}
          kustomize edit set image ${{ secrets.DOCKERHUB_USER }}/fastapi:${{ env.IMAGE_TAG }}

      - name: Commit cambios de kustomization
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          cd Servidor3/k8s
          if git diff --quiet kustomization.yaml; then
            echo "No hay cambios en kustomization.yaml"
          else
            git add kustomization.yaml
            git commit -m "chore: actualizar imágenes a tag ${{ env.IMAGE_TAG }}"
            git push origin main
          fi
